/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:136612ad-56f0-4050-91d7-e175663f026d",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_JjAddawIj",
    "aws_user_pools_web_client_id": "7kfequid27te1k4jve57nnarnp",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://zikfcygvmbavrou5khkpbjbx7e.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ws7ue7lijfdetgjsztvmjjts3q"
};


export default awsmobile;
